### ISSUE TITLE
Support mParticle-Apple-SDK 8.0

### ISSUE THREAD

**Issue by samuelcai-chancetop** [mParticle/react-native-mparticle#20]
In mParticle-Apple-SDK 8.0, the method setUserIdentity in MPIdentityApiRequest is changed, need to update accordingly.

**Comment by samuelcai-chancetop** [comment]
iOS 14 is released, and also the mParticle-Apple-SDK 8.0.1.

**Comment by BrandonStalnaker** [comment]
Thanks for the heads up. We're working on a change for this and it will most likely be released by next week.

**Comment by caisd1998** [comment]
@BrandonStalnaker is this done? I can see there is a 2.4.4 for iOS 14, but when I used it (also use mParticle-Apple-SDK 8), I still have compilation error, see screen shot attached, looks like the userIdentities method was deleted
<img width="1278" alt="Screen Shot 2020-10-10 at 16 38 13" src="https://user-images.githubusercontent.com/14158488/95650570-015da600-0b17-11eb-9702-ca7c27f8a8ce.png">

**Comment by samuelcai-chancetop** [comment]
@BrandonStalnaker is this done? I can see there is a 2.4.4 for iOS 14, but when I used it (also use mParticle-Apple-SDK 8), I still have compilation error, see screen shot attached, looks like the userIdentities method was deleted.
<img width="1279" alt="Screen Shot 2020-10-10 at 16 47 21" src="https://user-images.githubusercontent.com/59716697/95650782-46360c80-0b18-11eb-860a-996a91fb418e.png">

**Comment by BrandonStalnaker** [comment]
@samuelcai-chancetop Sorry about this. It looks like we had some merge issue on private that we didn't realize made it. 2.4.5 solves your issue.

**Comment by samuelcai-chancetop** [comment]
@BrandonStalnaker if this is fixed, can you mark this issue as resolved?
