### ISSUE TITLE
Support commerce event custom attributes

### ISSUE THREAD

**Issue by samuelcai-chancetop** [mParticle/react-native-mparticle#21]
The native sdk supports commerce event custom attributes, but this react native sdk doesn't support it.
Android example: builder = new CommerceEvent.Builder(productAction, product).transactionAttributes(transactionAttributes).customAttributes(customAttributes);

I made a patch based on 2.4.1, see attached.
[react-native-mparticle+2.4.1.patch.zip](https://github.com/mParticle/react-native-mparticle/files/5186900/react-native-mparticle%2B2.4.1.patch.zip)

**Comment by BrandonStalnaker** [comment]
MPEvents also cover customAttributes through the 'info' field which maps directly to customAttributes
