### ISSUE TITLE
fatal error: 'mParticle.h' file not found

### ISSUE THREAD

**Issue by jhackGC** [mParticle/react-native-mparticle#3]
HI! After installing the SDK and installing the RN package and linking it, the file 

node_modules/react-native-mparticle/ios/RNMParticle/RNMParticle.m:2:9: fatal error: 'mParticle.h' file not found

the RNMParticle.h file can't find the import "mParticle.h"

#import "mParticle.h"
I tried also #import <mParticle_Apple_SDK/mParticle.h>

and didn't work,

Any suggestion will be appreciated, 
Thanks

**Comment by jhackGC** [comment]
Hi there, the issue looks like its because the RNMParticle bridge believes the SDK has been installed with Cocoapods

as I can see something in the project.pbxproj file for the Bridge

in the file: 

...node_modules/react-native-mparticle/ios/RNMParticle.xcodeproj/project.pbxproj

I see 

USER_HEADER_SEARCH_PATHS = “$(SRCROOT)/../../../ios/Pods/mParticle-Apple-SDK/mParticle-Apple-SDK/** $(SRCROOT)/../../../Pods/mParticle-Apple-SDK/mParticle-Apple-SDK/** $(SRCROOT)/../sample/ios/Pods/mParticle-Apple-SDK/mParticle-Apple-SDK/**“;

We installed the SDK with Carthage

I wonder if we can “migrate” this classpath to Carthage style ...

**Comment by samdozor** [comment]
hey @jhackGC ! Always a good time making both Carthage and Cocoapods..and React happy :)

We'll take a look at this - if you see an easy change we'd be happy to accept a PR.

**Comment by jhackGC** [comment]
Hi Sam,
Thanks a lot for your response, but I think the team will move to Cocoapods, so it shouldn't be a problem anymore.
Cheers

**Comment by shr-GE** [comment]
i am facing this issue again. i am using version 2.7.7  with Xcode 14  , any ideas on how to resolve this?

**Comment by BrandonStalnaker** [comment]
@shr-GE Are you integrating with Carthage or Cocoapods?

**Comment by shr-GE** [comment]
@BrandonStalnaker i am installing with cocoapods . i have noticed this issue everytime i do pod install

**Comment by BrandonStalnaker** [comment]
@shr-GE @tdraper-dev  There's several possible reasons you could be getting this error that are all different implementation issues. 1st make sure you're setting up your podfile [according to the latest README](https://github.com/mParticle/react-native-mparticle?tab=readme-ov-file#ios). 

You should also update your import statements for mParticle [to this](https://github.com/mParticle/react-native-mparticle?tab=readme-ov-file#ios). 

My final suggestion for now is to get on the latest version of Xcode. Major architectural changes have occurred in React Native's recent releases and from Xcode 14 to 15. Additionally Xcode 15 will be required to release to the app store in the coming months

If none of this works please post additional information about whats steps you took to integrate mParticle and how your implementing us.
