### ISSUE TITLE
iOS: TypeError: null is not an object (evaluating '_reactNative.NativeModules.Mparticle.setUserAttributeArray')

### ISSUE THREAD

**Issue by markgibaud-vtail** [mParticle/react-native-mparticle#37]
Hi there,

Not sure why this is as I can see the method existing in the iOS code, but I'm getting this error when using passing an array to `setUserAttribute`.

This works:
<img width="388" alt="Screenshot 2021-04-08 at 14 43 37" src="https://user-images.githubusercontent.com/69155380/114037753-29855200-9879-11eb-94d0-a81a0ce4fc0d.png">

Resulting in:
<img width="807" alt="Screenshot 2021-04-08 at 14 45 43" src="https://user-images.githubusercontent.com/69155380/114037838-3dc94f00-9879-11eb-9574-9e9eabedf10f.png">

However simply changing the code to 
<img width="499" alt="Screenshot 2021-04-08 at 14 46 30" src="https://user-images.githubusercontent.com/69155380/114037908-4faaf200-9879-11eb-8774-4eb06e6104e1.png">

Results in
<img width="683" alt="Screenshot 2021-04-08 at 14 44 14" src="https://user-images.githubusercontent.com/69155380/114038084-79641900-9879-11eb-9825-05be23f8286e.png">

I have the latest npm and ios pods, this is my podfile.lock.

<img width="447" alt="Screenshot 2021-04-08 at 14 44 33" src="https://user-images.githubusercontent.com/69155380/114038504-d52ea200-9879-11eb-8120-ff2a0331c473.png">

Appreciate if this could be debugged 🙏

**Comment by markgibaud-vtail** [comment]
Solved by explicitly using `setUserAttributeArray`. I thought this check was done underneath here:

https://github.com/mParticle/react-native-mparticle/blob/master/js/index.js#L163

But perhaps I'm misreading something. However I now have this code which works and looks familiar!

```
if (event.value.constructor === Array) {
          currentUser.setUserAttributeArray(event.userAttribute, event.value);
        } else {
          currentUser.setUserAttribute(event.userAttribute, event.value);
        }
```

**Comment by samdozor** [comment]
@markgibaud-vtail thanks for the issue - took me a little while and a rubbing my eyes a few times to figure it out. 

Syntax error: "NativeModules.Mparticle.setUserAttributeArray(this.userId, key, value)"

should be `MParticle.setUserAttributeArray` (capital P)

Sounds like you have a workaround but reopening this bug so we can get it addressed.

**Comment by BrandonStalnaker** [comment]
Closed by https://github.com/mParticle/react-native-mparticle/commit/6d2461da38ba6a9820b0aa1336c6d9a37456c976
