### ISSUE TITLE
Environment setup?

### ISSUE THREAD

**Issue by IceDev-xyz** [mParticle/react-native-mparticle#43]
Is it possible to setup to diff environments like in the Node SDK.

```var batch = new mParticle.Batch(mParticle.Batch.Environment.development);```

I've search in the entire lib and found nothing related to environments.

**Comment by willpassidomo** [comment]
Hey @IceDev-xyz . I'm so sorry this has sat for so long, it seems like our webhook for public issues was never set up properly. 

The Environment can be set in each of the Native SDK's `start()` methods via `MParticleOptions`. The React Native SDK differs from the Node SDK in that it acts as a wrapper around out Native SDKS (which are stateful, environment is only set on initialization then subsequently attached to every Batch) as opposed to out Node SDK (which is stateless, environment must be set on every Batch individually)

For more information about setting the environment: 
[Android Docs](https://mparticle.tpondemand.com/RestUI/Board.aspx#page=board/5345919720762925434&appConfig=eyJhY2lkIjoiQkU5NjQ2QzRCNURDOTIxRkI1NEZFQzEwRkZFRUNDODkifQ==&boardPopup=feature/71485)
[iOS Docs](https://mparticle.tpondemand.com/RestUI/Board.aspx#page=board/5345919720762925434&appConfig=eyJhY2lkIjoiQkU5NjQ2QzRCNURDOTIxRkI1NEZFQzEwRkZFRUNDODkifQ==&boardPopup=feature/71485)
