### ISSUE TITLE
Value cannot be cast from Boolean to String

### ISSUE THREAD

**Issue by cheng-kang** [mParticle/react-native-mparticle#45]
Hi,

I'm using `react-native-mparticle@2.4.12` and experiencing the issue in the screenshot on **Android**. `is_prepay` is a boolean value attribute in the event, it works fine on iOS.

My workaround for now is:

```
track(event) {
    const payload = { ...event.payload };
    // MParticleModule for Android somehow tries to cast Boolean to String which would crash the app.
    if (Platform.OS === "android") {
      Object.keys(payload).forEach((key) => {
        if (typeof payload[key] === "boolean") {
          payload[key] = String(payload[key]);
        }
      })
    }
    MParticle.logEvent(event.name, MPaticle.EventType.Other, payload);
}
```

Could you help me to understand the situation here? Did I miss any docs about this issue? Or is this a bug?

<img src="https://user-images.githubusercontent.com/8396515/127474982-44ed7754-1599-4f41-b106-02fc1675d705.png" width=300 />

**Comment by markgibaud-vtail** [comment]
I have encountered the same issue when trying to log a `number` in the event attributes.

On closer inspection of the source, it looks like only `String` is supported for now:

https://github.com/mParticle/react-native-mparticle/blob/master/android/src/main/java/com/mparticle/react/MParticleModule.java#L65

@willpassidomo any chance this can be fixed to facilitate `boolean` and `number` too? Would really help with downstream analytics querying capabilities (eg. range queries on event attribute data when logging `number`s).

**Comment by willpassidomo** [comment]
Hey Mark,
So, this is a bit unfortunate, but we our backend is setup to ingest all
custom attribute values as Strings. We do have a number of integrations
that, provided they are capable of accepting other primitive-like types, we
will automatically convert into Number, Bool, Int etc if it can be
converted.

Do you have a particular integration in mind where it would help for these
attributes to type cast? I could check if it is already available as a
setting in our forwarder or at least give you an idea if it's something we
could add to it.

Thanks for reaching out,
Will

**Comment by willpassidomo** [comment]
@cheng-kang I'm so sorry this sat for so long! We were under the impression we had set up webhooks for all of our repositories, but this one seems to have slipped under the radar. I just opened a PR (referenced above) for this issue and it should be released shortly

**Comment by willpassidomo** [comment]
PR was merged and this will be included in the next release!

**Comment by markgibaud-vtail** [comment]
@willpassidomo thanks for coming back. As an example we're sending through the number of images sent as attachments in a `MessageSent` event, and server-side forwarding to Mixpanel, but Mixpanel seems to ingest as a string and so we can't do range queries for example:

<img width="348" alt="Screenshot 2021-09-08 at 16 37 45" src="https://user-images.githubusercontent.com/69155380/132540493-3db0328c-30c1-4989-92b2-fc9845730c08.png">

<img width="322" alt="Screenshot 2021-09-08 at 16 36 03" src="https://user-images.githubusercontent.com/69155380/132540501-0e8d762e-5d3d-47d5-a0d1-9219facbcc3a.png">

<img width="381" alt="Screenshot 2021-09-08 at 16 35 57" src="https://user-images.githubusercontent.com/69155380/132540508-c13882ba-84c9-4ba6-b2ea-b4af9ff6fd40.png">

**Comment by dsf3449** [comment]
@willpassidomo Any idea if this change will be released? I ran into this issue upgrading from react native 0.63.4 to 0.64.0
