### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by Mathew79** [mParticle/react-native-mparticle#50]
following line causes Compilation

   if json[@"shouldUploadEvent"] != nil {
        event.shouldUploadEvent = [json[@"shouldUploadEvent"] boolValue]
    }

**Comment by markgibaud-vtail** [comment]
Same issue (this is for iOS btw)

**Comment by BrandonStalnaker** [comment]
Fixed in version 2.5.0 
in commit https://github.com/mParticle/react-native-mparticle/commit/1c4cfaf0577a81066e438cc2dc88795efa8276a3
