### ISSUE TITLE
Could not invoke MParticle.logEvent

### ISSUE THREAD

**Issue by dsf3449** [mParticle/react-native-mparticle#69]
I updated to `2.7.0` which fixed the compile time error (as described in https://github.com/mParticle/react-native-mparticle/pull/68), but now when the app is actually running, I receive this error:

```
Could not invoke MParticle.logEvent

null

No virtual method info(Ljava/util/map;)Lcom/mparticle/MPEvent$Builder;
in class Lcom/mparticle/MPEvent$Builder;
or its super classes (declaration of 'com.mparticle.MPEvent$Builder' appears in
/data/app/~~3vP3w5TCBYkUUwsEB4-Bog==/<redacted>-4cbNUmsn0n_RM_K_H2Pozg==/base.apk!classes6.dex)
```

There was no issue before the new android release from yesterday.

Any advice?

**Comment by willpassidomo** [comment]
Hey @dsf3449 , that is interesting. The quick-fix we released put an upper-bound on the transitive dependency for `android-core` to < 5.39.0; are you able to tell which version of `android-core` the project is building with?

**Comment by dsf3449** [comment]
@willpassidomo Oops, sorry, this is my bad!

We followed the example in the [setup docs](https://docs.mparticle.com/developers/sdk/android/getting-started/):
`implementation 'com.mparticle:android-core:5+'`
in our `android/app/build.gradle`

I suppose this declaration takes precedence of what's in this repo, I just set it to:
`implementation 'com.mparticle:android-core:5.38.2'` instead and it works again.

Thanks for the quick response!

**Comment by willpassidomo** [comment]
Ah, good callout @dsf3449. I just realized the transitive dependency we locked is _only_ a compile dependency...my advice was incorrect, but I'm glad it at least pointed you in the right direction :) I'm currently updating our CI so we catch this kind of issue in the future
