### ISSUE TITLE
Question: Is autolinking supported?

### ISSUE THREAD

**Issue by lranches-gemini** [mParticle/react-native-mparticle#72]
Does this react native library support Autolinking? or do we have to really manually link the library? Autolinking seems to be the way to go nowadays since React Native 0.60. Also, if not is there a plan to support autolinking?

The current installation documents specifically say to use `react-native link`. 

If this still is this case this should be `npx react-native link react-native-mparticle` to isolate linking to that specific library.

**Comment by willpassidomo** [comment]
Hey @lranches-gemini I do not believe we do. That seems like a very useful feature for us to cut down on the friction of installing our plugin. I will open up a feature request with our team and post back in this issue when I get an idea of the timeline. Thanks for the request!

**Comment by lranches-gemini** [comment]
@willpassidomo Awesome, yes I think autolinking would help save a ton of time, I've had to piece the installation together by looking at the ios android native docs as well as looking at the example project. A combination of the those two sources got the project working properly. But yes, due to ease and developer productivity, autolinking is worth the time.

![Screen Shot 2022-05-25 at 11 24 08 AM](https://user-images.githubusercontent.com/89813159/170339251-90d6833f-e805-49f4-980d-c5d27024a503.png)
